name: drupal9
recipe: drupal9
config:
  php: 7.4
  database: mariadb
  webroot: web
  xdebug: off

# Get nice URLs for solr service.
proxy:
  search:
    - search.uniteweb2.lndo.site:8983

services:
  appserver:
    build:
      - composer install
  # Spin up a Solr container called "search".
  # Set "search" instead of "localhost"
  # on the Drupal search api solr server configuration.
  search:
    # Use a specific Solr version.
    type: solr:8
    # Optionally declare the name of the Solr core.
    # This setting is only applicable for versions 5.5 and above.
    core: drupal
    portforward: true
    # This should be the directory containing the schema.xml and solrconfig.xml files.
    # Download the config.zip and extract it.
    config:
      dir: solr/conf
  # Node container for frontend operations.
  node:
    type: node
    globals:
      gulp-cli: latest
tooling:
  reload-local:
    description: Reload your local environment doing a fresh install for testing or development
    cmd:
      - appserver: composer install
      # Install Drupal under the uw_profile.
      - appserver: drush -y site-install standard regional_settings.site_default_country="US" --account-mail='drupal@drupal.org' --site-name='Drupal 9' --site-mail='drupal@drupal.org'
      
      - appserver: drush theme:enable gin -y
      - appserver: drush config-set system.theme admin gin -y
      - appserver: drush en gin_toolbar gin_lb admin_toolbar -y
      - appserver: drush config-set gin.settings enable_darkmode 1 -y
      - appserver: drush config-set gin.settings high_contrast_mode 1 -y
      - appserver: drush config-set gin.settings classic_toolbar classic -y
      
      - appserver: drush en devel -y
      - appserver: drush config-set devel.settings devel_dumper kint -y
      - appserver: drush cr
      - appserver: drush uli  
  npm:
    service: node
  gulp:
    service: node
  phpcs:
    service: appserver
    description: Run code sniffer to check if code respect codding standard and Drupal best practices.
    cmd:
      - ./vendor/bin/phpcs
